// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: executor.proto

package aenvexecutorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED Effect = 0
	Effect_NO_EFFECT          Effect = 1
	Effect_COMPLETED          Effect = 2
	Effect_EFFECT_UNKNOWN     Effect = 3
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "NO_EFFECT",
		2: "COMPLETED",
		3: "EFFECT_UNKNOWN",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"NO_EFFECT":          1,
		"COMPLETED":          2,
		"EFFECT_UNKNOWN":     3,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_executor_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

type NetworkPolicy_Base int32

const (
	NetworkPolicy_DEFAULT NetworkPolicy_Base = 0
	NetworkPolicy_ALLOW   NetworkPolicy_Base = 1
	NetworkPolicy_DENY    NetworkPolicy_Base = 2
)

// Enum value maps for NetworkPolicy_Base.
var (
	NetworkPolicy_Base_name = map[int32]string{
		0: "DEFAULT",
		1: "ALLOW",
		2: "DENY",
	}
	NetworkPolicy_Base_value = map[string]int32{
		"DEFAULT": 0,
		"ALLOW":   1,
		"DENY":    2,
	}
)

func (x NetworkPolicy_Base) Enum() *NetworkPolicy_Base {
	p := new(NetworkPolicy_Base)
	*p = x
	return p
}

func (x NetworkPolicy_Base) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicy_Base) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_proto_enumTypes[1].Descriptor()
}

func (NetworkPolicy_Base) Type() protoreflect.EnumType {
	return &file_executor_proto_enumTypes[1]
}

func (x NetworkPolicy_Base) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicy_Base.Descriptor instead.
func (NetworkPolicy_Base) EnumDescriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10, 0}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	WorkerInstanceId string                 `protobuf:"bytes,2,opt,name=worker_instance_id,json=workerInstanceId,proto3" json:"worker_instance_id,omitempty"`
	MaxActors        uint32                 `protobuf:"varint,3,opt,name=max_actors,json=maxActors,proto3" json:"max_actors,omitempty"`
	Capabilities     []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxDevices       uint32                 `protobuf:"varint,5,opt,name=max_devices,json=maxDevices,proto3" json:"max_devices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetWorkerInstanceId() string {
	if x != nil {
		return x.WorkerInstanceId
	}
	return ""
}

func (x *CapabilitiesResponse) GetMaxActors() uint32 {
	if x != nil {
		return x.MaxActors
	}
	return 0
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CapabilitiesResponse) GetMaxDevices() uint32 {
	if x != nil {
		return x.MaxDevices
	}
	return 0
}

type Fence struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion      string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ActorUid             string                 `protobuf:"bytes,2,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	WorkerPodUid         string                 `protobuf:"bytes,3,opt,name=worker_pod_uid,json=workerPodUid,proto3" json:"worker_pod_uid,omitempty"`
	WorkerEpoch          uint64                 `protobuf:"varint,4,opt,name=worker_epoch,json=workerEpoch,proto3" json:"worker_epoch,omitempty"`
	WorkerInstanceId     string                 `protobuf:"bytes,5,opt,name=worker_instance_id,json=workerInstanceId,proto3" json:"worker_instance_id,omitempty"`
	AssignmentGeneration uint64                 `protobuf:"varint,6,opt,name=assignment_generation,json=assignmentGeneration,proto3" json:"assignment_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Fence) Reset() {
	*x = Fence{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fence) ProtoMessage() {}

func (x *Fence) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fence.ProtoReflect.Descriptor instead.
func (*Fence) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *Fence) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Fence) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *Fence) GetWorkerPodUid() string {
	if x != nil {
		return x.WorkerPodUid
	}
	return ""
}

func (x *Fence) GetWorkerEpoch() uint64 {
	if x != nil {
		return x.WorkerEpoch
	}
	return 0
}

func (x *Fence) GetWorkerInstanceId() string {
	if x != nil {
		return x.WorkerInstanceId
	}
	return ""
}

func (x *Fence) GetAssignmentGeneration() uint64 {
	if x != nil {
		return x.AssignmentGeneration
	}
	return 0
}

// Carried unchanged from the lifecycle authority through atelet to the adapter.
type LifecycleOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleOperation) Reset() {
	*x = LifecycleOperation{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleOperation) ProtoMessage() {}

func (x *LifecycleOperation) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleOperation.ProtoReflect.Descriptor instead.
func (*LifecycleOperation) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *LifecycleOperation) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *LifecycleOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type OperationRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Fence       *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	OperationId string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// SHA-256 of the deterministic protobuf encoding of command, lowercase hex.
	PayloadDigest      string   `protobuf:"bytes,3,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	DeadlineUnixMillis int64    `protobuf:"varint,4,opt,name=deadline_unix_millis,json=deadlineUnixMillis,proto3" json:"deadline_unix_millis,omitempty"`
	Command            *Command `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *OperationRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *OperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRequest) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *OperationRequest) GetDeadlineUnixMillis() int64 {
	if x != nil {
		return x.DeadlineUnixMillis
	}
	return 0
}

func (x *OperationRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*Command_Start
	//	*Command_Restore
	//	*Command_Capture
	//	*Command_Stop
	//	*Command_UpdatePolicy
	//	*Command_UpdateExtensions
	Action        isCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetAction() isCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Command) GetStart() *LaunchSpec {
	if x != nil {
		if x, ok := x.Action.(*Command_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Command) GetRestore() *RestoreSpec {
	if x != nil {
		if x, ok := x.Action.(*Command_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Command) GetCapture() *CaptureSpec {
	if x != nil {
		if x, ok := x.Action.(*Command_Capture); ok {
			return x.Capture
		}
	}
	return nil
}

func (x *Command) GetStop() *StopSpec {
	if x != nil {
		if x, ok := x.Action.(*Command_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Command) GetUpdatePolicy() *NetworkPolicy {
	if x != nil {
		if x, ok := x.Action.(*Command_UpdatePolicy); ok {
			return x.UpdatePolicy
		}
	}
	return nil
}

func (x *Command) GetUpdateExtensions() *ExtensionParams {
	if x != nil {
		if x, ok := x.Action.(*Command_UpdateExtensions); ok {
			return x.UpdateExtensions
		}
	}
	return nil
}

type isCommand_Action interface {
	isCommand_Action()
}

type Command_Start struct {
	Start *LaunchSpec `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type Command_Restore struct {
	Restore *RestoreSpec `protobuf:"bytes,2,opt,name=restore,proto3,oneof"`
}

type Command_Capture struct {
	Capture *CaptureSpec `protobuf:"bytes,3,opt,name=capture,proto3,oneof"`
}

type Command_Stop struct {
	Stop *StopSpec `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type Command_UpdatePolicy struct {
	UpdatePolicy *NetworkPolicy `protobuf:"bytes,5,opt,name=update_policy,json=updatePolicy,proto3,oneof"`
}

type Command_UpdateExtensions struct {
	UpdateExtensions *ExtensionParams `protobuf:"bytes,6,opt,name=update_extensions,json=updateExtensions,proto3,oneof"`
}

func (*Command_Start) isCommand_Action() {}

func (*Command_Restore) isCommand_Action() {}

func (*Command_Capture) isCommand_Action() {}

func (*Command_Stop) isCommand_Action() {}

func (*Command_UpdatePolicy) isCommand_Action() {}

func (*Command_UpdateExtensions) isCommand_Action() {}

type LaunchSpec struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ImageDigest         string                 `protobuf:"bytes,1,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	ImageConfigPath     string                 `protobuf:"bytes,2,opt,name=image_config_path,json=imageConfigPath,proto3" json:"image_config_path,omitempty"`
	Argv                []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	Env                 []*EnvVar              `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Cwd                 string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User                string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Vcpus               uint32                 `protobuf:"varint,7,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMib           uint64                 `protobuf:"varint,8,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	RootfsBytes         uint64                 `protobuf:"varint,9,opt,name=rootfs_bytes,json=rootfsBytes,proto3" json:"rootfs_bytes,omitempty"`
	Network             *NetworkAttachment     `protobuf:"bytes,10,opt,name=network,proto3" json:"network,omitempty"`
	Assets              []*RuntimeAsset        `protobuf:"bytes,11,rep,name=assets,proto3" json:"assets,omitempty"`
	Drives              []*Drive               `protobuf:"bytes,12,rep,name=drives,proto3" json:"drives,omitempty"`
	EnvdAccessToken     string                 `protobuf:"bytes,13,opt,name=envd_access_token,json=envdAccessToken,proto3" json:"envd_access_token,omitempty"`
	Extensions          *ExtensionParams       `protobuf:"bytes,14,opt,name=extensions,proto3" json:"extensions,omitempty"`
	CompatibilityDomain string                 `protobuf:"bytes,15,opt,name=compatibility_domain,json=compatibilityDomain,proto3" json:"compatibility_domain,omitempty"`
	// Adapter-owned allocation-local cgroup, never a portable snapshot path.
	CgroupPath    string `protobuf:"bytes,16,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	ExtraBootArgs string `protobuf:"bytes,17,opt,name=extra_boot_args,json=extraBootArgs,proto3" json:"extra_boot_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSpec) Reset() {
	*x = LaunchSpec{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSpec) ProtoMessage() {}

func (x *LaunchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSpec.ProtoReflect.Descriptor instead.
func (*LaunchSpec) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchSpec) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *LaunchSpec) GetImageConfigPath() string {
	if x != nil {
		return x.ImageConfigPath
	}
	return ""
}

func (x *LaunchSpec) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *LaunchSpec) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *LaunchSpec) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *LaunchSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LaunchSpec) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *LaunchSpec) GetMemoryMib() uint64 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *LaunchSpec) GetRootfsBytes() uint64 {
	if x != nil {
		return x.RootfsBytes
	}
	return 0
}

func (x *LaunchSpec) GetNetwork() *NetworkAttachment {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *LaunchSpec) GetAssets() []*RuntimeAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *LaunchSpec) GetDrives() []*Drive {
	if x != nil {
		return x.Drives
	}
	return nil
}

func (x *LaunchSpec) GetEnvdAccessToken() string {
	if x != nil {
		return x.EnvdAccessToken
	}
	return ""
}

func (x *LaunchSpec) GetExtensions() *ExtensionParams {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *LaunchSpec) GetCompatibilityDomain() string {
	if x != nil {
		return x.CompatibilityDomain
	}
	return ""
}

func (x *LaunchSpec) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *LaunchSpec) GetExtraBootArgs() string {
	if x != nil {
		return x.ExtraBootArgs
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RuntimeAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeAsset) Reset() {
	*x = RuntimeAsset{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeAsset) ProtoMessage() {}

func (x *RuntimeAsset) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeAsset.ProtoReflect.Descriptor instead.
func (*RuntimeAsset) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RuntimeAsset) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type NetworkAttachment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NetnsPath           string                 `protobuf:"bytes,1,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	TapName             string                 `protobuf:"bytes,2,opt,name=tap_name,json=tapName,proto3" json:"tap_name,omitempty"`
	GuestIpv4           string                 `protobuf:"bytes,3,opt,name=guest_ipv4,json=guestIpv4,proto3" json:"guest_ipv4,omitempty"`
	GatewayIpv4         string                 `protobuf:"bytes,4,opt,name=gateway_ipv4,json=gatewayIpv4,proto3" json:"gateway_ipv4,omitempty"`
	GuestMac            string                 `protobuf:"bytes,5,opt,name=guest_mac,json=guestMac,proto3" json:"guest_mac,omitempty"`
	Mtu                 uint32                 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Policy              *NetworkPolicy         `protobuf:"bytes,7,opt,name=policy,proto3" json:"policy,omitempty"`
	InteractionIpv4     string                 `protobuf:"bytes,8,opt,name=interaction_ipv4,json=interactionIpv4,proto3" json:"interaction_ipv4,omitempty"`
	Netmask             string                 `protobuf:"bytes,9,opt,name=netmask,proto3" json:"netmask,omitempty"`
	DnsIpv4             string                 `protobuf:"bytes,10,opt,name=dns_ipv4,json=dnsIpv4,proto3" json:"dns_ipv4,omitempty"`
	PlatformDeniedCidrs []string               `protobuf:"bytes,11,rep,name=platform_denied_cidrs,json=platformDeniedCidrs,proto3" json:"platform_denied_cidrs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetworkAttachment) Reset() {
	*x = NetworkAttachment{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAttachment) ProtoMessage() {}

func (x *NetworkAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAttachment.ProtoReflect.Descriptor instead.
func (*NetworkAttachment) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkAttachment) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

func (x *NetworkAttachment) GetTapName() string {
	if x != nil {
		return x.TapName
	}
	return ""
}

func (x *NetworkAttachment) GetGuestIpv4() string {
	if x != nil {
		return x.GuestIpv4
	}
	return ""
}

func (x *NetworkAttachment) GetGatewayIpv4() string {
	if x != nil {
		return x.GatewayIpv4
	}
	return ""
}

func (x *NetworkAttachment) GetGuestMac() string {
	if x != nil {
		return x.GuestMac
	}
	return ""
}

func (x *NetworkAttachment) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkAttachment) GetPolicy() *NetworkPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *NetworkAttachment) GetInteractionIpv4() string {
	if x != nil {
		return x.InteractionIpv4
	}
	return ""
}

func (x *NetworkAttachment) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

func (x *NetworkAttachment) GetDnsIpv4() string {
	if x != nil {
		return x.DnsIpv4
	}
	return ""
}

func (x *NetworkAttachment) GetPlatformDeniedCidrs() []string {
	if x != nil {
		return x.PlatformDeniedCidrs
	}
	return nil
}

type NetworkPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          NetworkPolicy_Base     `protobuf:"varint,1,opt,name=base,proto3,enum=agentenv.executor.v1.NetworkPolicy_Base" json:"base,omitempty"`
	AllowOut      []string               `protobuf:"bytes,2,rep,name=allow_out,json=allowOut,proto3" json:"allow_out,omitempty"`
	DenyOut       []string               `protobuf:"bytes,3,rep,name=deny_out,json=denyOut,proto3" json:"deny_out,omitempty"`
	Revision      uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkPolicy) GetBase() NetworkPolicy_Base {
	if x != nil {
		return x.Base
	}
	return NetworkPolicy_DEFAULT
}

func (x *NetworkPolicy) GetAllowOut() []string {
	if x != nil {
		return x.AllowOut
	}
	return nil
}

func (x *NetworkPolicy) GetDenyOut() []string {
	if x != nil {
		return x.DenyOut
	}
	return nil
}

func (x *NetworkPolicy) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ExtensionParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionParams) Reset() {
	*x = ExtensionParams{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionParams) ProtoMessage() {}

func (x *ExtensionParams) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionParams.ProtoReflect.Descriptor instead.
func (*ExtensionParams) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *ExtensionParams) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type Drive struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageConfigPath string                 `protobuf:"bytes,2,opt,name=image_config_path,json=imageConfigPath,proto3" json:"image_config_path,omitempty"`
	MountPath       string                 `protobuf:"bytes,3,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly        bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	VirtualSize     uint64                 `protobuf:"varint,5,opt,name=virtual_size,json=virtualSize,proto3" json:"virtual_size,omitempty"`
	VolumeUid       string                 `protobuf:"bytes,6,opt,name=volume_uid,json=volumeUid,proto3" json:"volume_uid,omitempty"`
	VolumeVersion   string                 `protobuf:"bytes,7,opt,name=volume_version,json=volumeVersion,proto3" json:"volume_version,omitempty"`
	ImageDigest     string                 `protobuf:"bytes,8,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	SubPath         string                 `protobuf:"bytes,9,opt,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Drive) Reset() {
	*x = Drive{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drive) ProtoMessage() {}

func (x *Drive) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drive.ProtoReflect.Descriptor instead.
func (*Drive) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *Drive) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Drive) GetImageConfigPath() string {
	if x != nil {
		return x.ImageConfigPath
	}
	return ""
}

func (x *Drive) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *Drive) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Drive) GetVirtualSize() uint64 {
	if x != nil {
		return x.VirtualSize
	}
	return 0
}

func (x *Drive) GetVolumeUid() string {
	if x != nil {
		return x.VolumeUid
	}
	return ""
}

func (x *Drive) GetVolumeVersion() string {
	if x != nil {
		return x.VolumeVersion
	}
	return ""
}

func (x *Drive) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *Drive) GetSubPath() string {
	if x != nil {
		return x.SubPath
	}
	return ""
}

type RestoreSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Launch         *LaunchSpec            `protobuf:"bytes,1,opt,name=launch,proto3" json:"launch,omitempty"`
	SnapshotDir    string                 `protobuf:"bytes,2,opt,name=snapshot_dir,json=snapshotDir,proto3" json:"snapshot_dir,omitempty"`
	ManifestSha256 string                 `protobuf:"bytes,3,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestoreSpec) Reset() {
	*x = RestoreSpec{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSpec) ProtoMessage() {}

func (x *RestoreSpec) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSpec.ProtoReflect.Descriptor instead.
func (*RestoreSpec) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreSpec) GetLaunch() *LaunchSpec {
	if x != nil {
		return x.Launch
	}
	return nil
}

func (x *RestoreSpec) GetSnapshotDir() string {
	if x != nil {
		return x.SnapshotDir
	}
	return ""
}

func (x *RestoreSpec) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

type CaptureSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OutputDir       string                 `protobuf:"bytes,1,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	ContinueRunning bool                   `protobuf:"varint,2,opt,name=continue_running,json=continueRunning,proto3" json:"continue_running,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureSpec) Reset() {
	*x = CaptureSpec{}
	mi := &file_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSpec) ProtoMessage() {}

func (x *CaptureSpec) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSpec.ProtoReflect.Descriptor instead.
func (*CaptureSpec) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{14}
}

func (x *CaptureSpec) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *CaptureSpec) GetContinueRunning() bool {
	if x != nil {
		return x.ContinueRunning
	}
	return false
}

type StopSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSpec) Reset() {
	*x = StopSpec{}
	mi := &file_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSpec) ProtoMessage() {}

func (x *StopSpec) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSpec.ProtoReflect.Descriptor instead.
func (*StopSpec) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{15}
}

type OperationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Effect                Effect                 `protobuf:"varint,1,opt,name=effect,proto3,enum=agentenv.executor.v1.Effect" json:"effect,omitempty"`
	OperationId           string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ErrorCode             string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SnapshotFiles         []string               `protobuf:"bytes,5,rep,name=snapshot_files,json=snapshotFiles,proto3" json:"snapshot_files,omitempty"`
	AppliedPolicyRevision uint64                 `protobuf:"varint,6,opt,name=applied_policy_revision,json=appliedPolicyRevision,proto3" json:"applied_policy_revision,omitempty"`
	ApprovedExtensions    *ExtensionParams       `protobuf:"bytes,7,opt,name=approved_extensions,json=approvedExtensions,proto3" json:"approved_extensions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{16}
}

func (x *OperationResponse) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

func (x *OperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *OperationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OperationResponse) GetSnapshotFiles() []string {
	if x != nil {
		return x.SnapshotFiles
	}
	return nil
}

func (x *OperationResponse) GetAppliedPolicyRevision() uint64 {
	if x != nil {
		return x.AppliedPolicyRevision
	}
	return 0
}

func (x *OperationResponse) GetApprovedExtensions() *ExtensionParams {
	if x != nil {
		return x.ApprovedExtensions
	}
	return nil
}

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{17}
}

func (x *InspectRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *InspectRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type InspectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Fence             *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Operation         *OperationResponse     `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	EnvdVersion       string                 `protobuf:"bytes,4,opt,name=envd_version,json=envdVersion,proto3" json:"envd_version,omitempty"`
	CurrentExtensions *ExtensionParams       `protobuf:"bytes,5,opt,name=current_extensions,json=currentExtensions,proto3" json:"current_extensions,omitempty"`
	RootfsBytes       uint64                 `protobuf:"varint,6,opt,name=rootfs_bytes,json=rootfsBytes,proto3" json:"rootfs_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{18}
}

func (x *InspectResponse) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *InspectResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InspectResponse) GetOperation() *OperationResponse {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *InspectResponse) GetEnvdVersion() string {
	if x != nil {
		return x.EnvdVersion
	}
	return ""
}

func (x *InspectResponse) GetCurrentExtensions() *ExtensionParams {
	if x != nil {
		return x.CurrentExtensions
	}
	return nil
}

func (x *InspectResponse) GetRootfsBytes() uint64 {
	if x != nil {
		return x.RootfsBytes
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{19}
}

func (x *StatsRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

// Guest counters, explicitly distinct from host cgroup accounting.
type StatsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Fence                *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	ObservedAtUnixMillis int64                  `protobuf:"varint,2,opt,name=observed_at_unix_millis,json=observedAtUnixMillis,proto3" json:"observed_at_unix_millis,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes     uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryCacheBytes     uint64                 `protobuf:"varint,5,opt,name=memory_cache_bytes,json=memoryCacheBytes,proto3" json:"memory_cache_bytes,omitempty"`
	CpuUsedPercent       float32                `protobuf:"fixed32,6,opt,name=cpu_used_percent,json=cpuUsedPercent,proto3" json:"cpu_used_percent,omitempty"`
	DiskUsedBytes        uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes       uint64                 `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	CpuCount             uint32                 `protobuf:"varint,9,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_executor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{20}
}

func (x *StatsResponse) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *StatsResponse) GetObservedAtUnixMillis() int64 {
	if x != nil {
		return x.ObservedAtUnixMillis
	}
	return 0
}

func (x *StatsResponse) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryCacheBytes() uint64 {
	if x != nil {
		return x.MemoryCacheBytes
	}
	return 0
}

func (x *StatsResponse) GetCpuUsedPercent() float32 {
	if x != nil {
		return x.CpuUsedPercent
	}
	return 0
}

func (x *StatsResponse) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *StatsResponse) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *StatsResponse) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

type ReconcileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerPodUid     string                 `protobuf:"bytes,1,opt,name=worker_pod_uid,json=workerPodUid,proto3" json:"worker_pod_uid,omitempty"`
	WorkerEpoch      uint64                 `protobuf:"varint,2,opt,name=worker_epoch,json=workerEpoch,proto3" json:"worker_epoch,omitempty"`
	WorkerInstanceId string                 `protobuf:"bytes,3,opt,name=worker_instance_id,json=workerInstanceId,proto3" json:"worker_instance_id,omitempty"`
	Assignments      []*Fence               `protobuf:"bytes,4,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_executor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{21}
}

func (x *ReconcileRequest) GetWorkerPodUid() string {
	if x != nil {
		return x.WorkerPodUid
	}
	return ""
}

func (x *ReconcileRequest) GetWorkerEpoch() uint64 {
	if x != nil {
		return x.WorkerEpoch
	}
	return 0
}

func (x *ReconcileRequest) GetWorkerInstanceId() string {
	if x != nil {
		return x.WorkerInstanceId
	}
	return ""
}

func (x *ReconcileRequest) GetAssignments() []*Fence {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type ReconcileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*InspectResponse     `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_executor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{22}
}

func (x *ReconcileResponse) GetActors() []*InspectResponse {
	if x != nil {
		return x.Actors
	}
	return nil
}

// Control-plane to atelet/adapter envelope. Execution must already be durable;
// a transport timeout does not acknowledge a policy revision.
type ApplyNetworkPolicyRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Execution          *LifecycleOperation    `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	ActorUid           string                 `protobuf:"bytes,2,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	TargetWorkerPodUid string                 `protobuf:"bytes,3,opt,name=target_worker_pod_uid,json=targetWorkerPodUid,proto3" json:"target_worker_pod_uid,omitempty"`
	Policy             *NetworkPolicy         `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyNetworkPolicyRequest) Reset() {
	*x = ApplyNetworkPolicyRequest{}
	mi := &file_executor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNetworkPolicyRequest) ProtoMessage() {}

func (x *ApplyNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{23}
}

func (x *ApplyNetworkPolicyRequest) GetExecution() *LifecycleOperation {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ApplyNetworkPolicyRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *ApplyNetworkPolicyRequest) GetTargetWorkerPodUid() string {
	if x != nil {
		return x.TargetWorkerPodUid
	}
	return ""
}

func (x *ApplyNetworkPolicyRequest) GetPolicy() *NetworkPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ApplyNetworkPolicyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppliedRevision uint64                 `protobuf:"varint,1,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyNetworkPolicyResponse) Reset() {
	*x = ApplyNetworkPolicyResponse{}
	mi := &file_executor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNetworkPolicyResponse) ProtoMessage() {}

func (x *ApplyNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*ApplyNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{24}
}

func (x *ApplyNetworkPolicyResponse) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

// Worker routing envelope; the executor itself receives only StatsRequest.
type ReadGuestStatsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Execution          *LifecycleOperation    `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	ActorUid           string                 `protobuf:"bytes,2,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	TargetWorkerPodUid string                 `protobuf:"bytes,3,opt,name=target_worker_pod_uid,json=targetWorkerPodUid,proto3" json:"target_worker_pod_uid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReadGuestStatsRequest) Reset() {
	*x = ReadGuestStatsRequest{}
	mi := &file_executor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGuestStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGuestStatsRequest) ProtoMessage() {}

func (x *ReadGuestStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGuestStatsRequest.ProtoReflect.Descriptor instead.
func (*ReadGuestStatsRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{25}
}

func (x *ReadGuestStatsRequest) GetExecution() *LifecycleOperation {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ReadGuestStatsRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *ReadGuestStatsRequest) GetTargetWorkerPodUid() string {
	if x != nil {
		return x.TargetWorkerPodUid
	}
	return ""
}

type ReadRuntimeInfoRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Execution          *LifecycleOperation    `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	ActorUid           string                 `protobuf:"bytes,2,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	TargetWorkerPodUid string                 `protobuf:"bytes,3,opt,name=target_worker_pod_uid,json=targetWorkerPodUid,proto3" json:"target_worker_pod_uid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReadRuntimeInfoRequest) Reset() {
	*x = ReadRuntimeInfoRequest{}
	mi := &file_executor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRuntimeInfoRequest) ProtoMessage() {}

func (x *ReadRuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*ReadRuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{26}
}

func (x *ReadRuntimeInfoRequest) GetExecution() *LifecycleOperation {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ReadRuntimeInfoRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *ReadRuntimeInfoRequest) GetTargetWorkerPodUid() string {
	if x != nil {
		return x.TargetWorkerPodUid
	}
	return ""
}

type ApplyExtensionParamsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Execution          *LifecycleOperation    `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	ActorUid           string                 `protobuf:"bytes,2,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	TargetWorkerPodUid string                 `protobuf:"bytes,3,opt,name=target_worker_pod_uid,json=targetWorkerPodUid,proto3" json:"target_worker_pod_uid,omitempty"`
	Patch              *ExtensionParams       `protobuf:"bytes,4,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyExtensionParamsRequest) Reset() {
	*x = ApplyExtensionParamsRequest{}
	mi := &file_executor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyExtensionParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyExtensionParamsRequest) ProtoMessage() {}

func (x *ApplyExtensionParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyExtensionParamsRequest.ProtoReflect.Descriptor instead.
func (*ApplyExtensionParamsRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{27}
}

func (x *ApplyExtensionParamsRequest) GetExecution() *LifecycleOperation {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ApplyExtensionParamsRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *ApplyExtensionParamsRequest) GetTargetWorkerPodUid() string {
	if x != nil {
		return x.TargetWorkerPodUid
	}
	return ""
}

func (x *ApplyExtensionParamsRequest) GetPatch() *ExtensionParams {
	if x != nil {
		return x.Patch
	}
	return nil
}

type ApplyExtensionParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      *ExtensionParams       `protobuf:"bytes,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Effect        Effect                 `protobuf:"varint,2,opt,name=effect,proto3,enum=agentenv.executor.v1.Effect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyExtensionParamsResponse) Reset() {
	*x = ApplyExtensionParamsResponse{}
	mi := &file_executor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyExtensionParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyExtensionParamsResponse) ProtoMessage() {}

func (x *ApplyExtensionParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyExtensionParamsResponse.ProtoReflect.Descriptor instead.
func (*ApplyExtensionParamsResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{28}
}

func (x *ApplyExtensionParamsResponse) GetApproved() *ExtensionParams {
	if x != nil {
		return x.Approved
	}
	return nil
}

func (x *ApplyExtensionParamsResponse) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x14agentenv.executor.v1\"\x15\n" +
	"\x13CapabilitiesRequest\"\xd3\x01\n" +
	"\x14CapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12,\n" +
	"\x12worker_instance_id\x18\x02 \x01(\tR\x10workerInstanceId\x12\x1d\n" +
	"\n" +
	"max_actors\x18\x03 \x01(\rR\tmaxActors\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vmax_devices\x18\x05 \x01(\rR\n" +
	"maxDevices\"\xfb\x01\n" +
	"\x05Fence\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tactor_uid\x18\x02 \x01(\tR\bactorUid\x12$\n" +
	"\x0eworker_pod_uid\x18\x03 \x01(\tR\fworkerPodUid\x12!\n" +
	"\fworker_epoch\x18\x04 \x01(\x04R\vworkerEpoch\x12,\n" +
	"\x12worker_instance_id\x18\x05 \x01(\tR\x10workerInstanceId\x123\n" +
	"\x15assignment_generation\x18\x06 \x01(\x04R\x14assignmentGeneration\"j\n" +
	"\x12LifecycleOperation\x121\n" +
	"\x05fence\x18\x01 \x01(\v2\x1b.agentenv.executor.v1.FenceR\x05fence\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"\xfa\x01\n" +
	"\x10OperationRequest\x121\n" +
	"\x05fence\x18\x01 \x01(\v2\x1b.agentenv.executor.v1.FenceR\x05fence\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12%\n" +
	"\x0epayload_digest\x18\x03 \x01(\tR\rpayloadDigest\x120\n" +
	"\x14deadline_unix_millis\x18\x04 \x01(\x03R\x12deadlineUnixMillis\x127\n" +
	"\acommand\x18\x05 \x01(\v2\x1d.agentenv.executor.v1.CommandR\acommand\"\xa3\x03\n" +
	"\aCommand\x128\n" +
	"\x05start\x18\x01 \x01(\v2 .agentenv.executor.v1.LaunchSpecH\x00R\x05start\x12=\n" +
	"\arestore\x18\x02 \x01(\v2!.agentenv.executor.v1.RestoreSpecH\x00R\arestore\x12=\n" +
	"\acapture\x18\x03 \x01(\v2!.agentenv.executor.v1.CaptureSpecH\x00R\acapture\x124\n" +
	"\x04stop\x18\x04 \x01(\v2\x1e.agentenv.executor.v1.StopSpecH\x00R\x04stop\x12J\n" +
	"\rupdate_policy\x18\x05 \x01(\v2#.agentenv.executor.v1.NetworkPolicyH\x00R\fupdatePolicy\x12T\n" +
	"\x11update_extensions\x18\x06 \x01(\v2%.agentenv.executor.v1.ExtensionParamsH\x00R\x10updateExtensionsB\b\n" +
	"\x06action\"\xc5\x05\n" +
	"\n" +
	"LaunchSpec\x12!\n" +
	"\fimage_digest\x18\x01 \x01(\tR\vimageDigest\x12*\n" +
	"\x11image_config_path\x18\x02 \x01(\tR\x0fimageConfigPath\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12.\n" +
	"\x03env\x18\x04 \x03(\v2\x1c.agentenv.executor.v1.EnvVarR\x03env\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x14\n" +
	"\x05vcpus\x18\a \x01(\rR\x05vcpus\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\b \x01(\x04R\tmemoryMib\x12!\n" +
	"\frootfs_bytes\x18\t \x01(\x04R\vrootfsBytes\x12A\n" +
	"\anetwork\x18\n" +
	" \x01(\v2'.agentenv.executor.v1.NetworkAttachmentR\anetwork\x12:\n" +
	"\x06assets\x18\v \x03(\v2\".agentenv.executor.v1.RuntimeAssetR\x06assets\x123\n" +
	"\x06drives\x18\f \x03(\v2\x1b.agentenv.executor.v1.DriveR\x06drives\x12/\n" +
	"\x11envd_access_token\x18\r \x01(\tB\x03\x80\x01\x01R\x0fenvdAccessToken\x12E\n" +
	"\n" +
	"extensions\x18\x0e \x01(\v2%.agentenv.executor.v1.ExtensionParamsR\n" +
	"extensions\x121\n" +
	"\x14compatibility_domain\x18\x0f \x01(\tR\x13compatibilityDomain\x12\x1f\n" +
	"\vcgroup_path\x18\x10 \x01(\tR\n" +
	"cgroupPath\x12&\n" +
	"\x0fextra_boot_args\x18\x11 \x01(\tR\rextraBootArgs\"7\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tB\x03\x80\x01\x01R\x05value\"N\n" +
	"\fRuntimeAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"\x8f\x03\n" +
	"\x11NetworkAttachment\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x01 \x01(\tR\tnetnsPath\x12\x19\n" +
	"\btap_name\x18\x02 \x01(\tR\atapName\x12\x1d\n" +
	"\n" +
	"guest_ipv4\x18\x03 \x01(\tR\tguestIpv4\x12!\n" +
	"\fgateway_ipv4\x18\x04 \x01(\tR\vgatewayIpv4\x12\x1b\n" +
	"\tguest_mac\x18\x05 \x01(\tR\bguestMac\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\x12;\n" +
	"\x06policy\x18\a \x01(\v2#.agentenv.executor.v1.NetworkPolicyR\x06policy\x12)\n" +
	"\x10interaction_ipv4\x18\b \x01(\tR\x0finteractionIpv4\x12\x18\n" +
	"\anetmask\x18\t \x01(\tR\anetmask\x12\x19\n" +
	"\bdns_ipv4\x18\n" +
	" \x01(\tR\adnsIpv4\x122\n" +
	"\x15platform_denied_cidrs\x18\v \x03(\tR\x13platformDeniedCidrs\"\xcb\x01\n" +
	"\rNetworkPolicy\x12<\n" +
	"\x04base\x18\x01 \x01(\x0e2(.agentenv.executor.v1.NetworkPolicy.BaseR\x04base\x12\x1b\n" +
	"\tallow_out\x18\x02 \x03(\tR\ballowOut\x12\x19\n" +
	"\bdeny_out\x18\x03 \x03(\tR\adenyOut\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\"(\n" +
	"\x04Base\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02\"*\n" +
	"\x0fExtensionParams\x12\x17\n" +
	"\x04json\x18\x01 \x01(\tB\x03\x80\x01\x01R\x04json\"\xa6\x02\n" +
	"\x05Drive\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11image_config_path\x18\x02 \x01(\tR\x0fimageConfigPath\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x03 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12!\n" +
	"\fvirtual_size\x18\x05 \x01(\x04R\vvirtualSize\x12\x1d\n" +
	"\n" +
	"volume_uid\x18\x06 \x01(\tR\tvolumeUid\x12%\n" +
	"\x0evolume_version\x18\a \x01(\tR\rvolumeVersion\x12!\n" +
	"\fimage_digest\x18\b \x01(\tR\vimageDigest\x12\x19\n" +
	"\bsub_path\x18\t \x01(\tR\asubPath\"\x93\x01\n" +
	"\vRestoreSpec\x128\n" +
	"\x06launch\x18\x01 \x01(\v2 .agentenv.executor.v1.LaunchSpecR\x06launch\x12!\n" +
	"\fsnapshot_dir\x18\x02 \x01(\tR\vsnapshotDir\x12'\n" +
	"\x0fmanifest_sha256\x18\x03 \x01(\tR\x0emanifestSha256\"W\n" +
	"\vCaptureSpec\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x01 \x01(\tR\toutputDir\x12)\n" +
	"\x10continue_running\x18\x02 \x01(\bR\x0fcontinueRunning\"\n" +
	"\n" +
	"\bStopSpec\"\xe7\x02\n" +
	"\x11OperationResponse\x124\n" +
	"\x06effect\x18\x01 \x01(\x0e2\x1c.agentenv.executor.v1.EffectR\x06effect\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0esnapshot_files\x18\x05 \x03(\tR\rsnapshotFiles\x126\n" +
	"\x17applied_policy_revision\x18\x06 \x01(\x04R\x15appliedPolicyRevision\x12V\n" +
	"\x13approved_extensions\x18\a \x01(\v2%.agentenv.executor.v1.ExtensionParamsR\x12approvedExtensions\"f\n" +
	"\x0eInspectRequest\x121\n" +
	"\x05fence\x18\x01 \x01(\v2\x1b.agentenv.executor.v1.FenceR\x05fence\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"\xbd\x02\n" +
	"\x0fInspectResponse\x121\n" +
	"\x05fence\x18\x01 \x01(\v2\x1b.agentenv.executor.v1.FenceR\x05fence\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12E\n" +
	"\toperation\x18\x03 \x01(\v2'.agentenv.executor.v1.OperationResponseR\toperation\x12!\n" +
	"\fenvd_version\x18\x04 \x01(\tR\venvdVersion\x12T\n" +
	"\x12current_extensions\x18\x05 \x01(\v2%.agentenv.executor.v1.ExtensionParamsR\x11currentExtensions\x12!\n" +
	"\frootfs_bytes\x18\x06 \x01(\x04R\vrootfsBytes\"A\n" +
	"\fStatsRequest\x121\n" +
	"\x05fence\x18\x01 \x01(\v2\x1b.agentenv.executor.v1.FenceR\x05fence\"\x9a\x03\n" +
	"\rStatsResponse\x121\n" +
	"\x05fence\x18\x01 \x01(\v2\x1b.agentenv.executor.v1.FenceR\x05fence\x125\n" +
	"\x17observed_at_unix_millis\x18\x02 \x01(\x03R\x14observedAtUnixMillis\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\x12,\n" +
	"\x12memory_cache_bytes\x18\x05 \x01(\x04R\x10memoryCacheBytes\x12(\n" +
	"\x10cpu_used_percent\x18\x06 \x01(\x02R\x0ecpuUsedPercent\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x04R\x0ediskTotalBytes\x12\x1b\n" +
	"\tcpu_count\x18\t \x01(\rR\bcpuCount\"\xc8\x01\n" +
	"\x10ReconcileRequest\x12$\n" +
	"\x0eworker_pod_uid\x18\x01 \x01(\tR\fworkerPodUid\x12!\n" +
	"\fworker_epoch\x18\x02 \x01(\x04R\vworkerEpoch\x12,\n" +
	"\x12worker_instance_id\x18\x03 \x01(\tR\x10workerInstanceId\x12=\n" +
	"\vassignments\x18\x04 \x03(\v2\x1b.agentenv.executor.v1.FenceR\vassignments\"R\n" +
	"\x11ReconcileResponse\x12=\n" +
	"\x06actors\x18\x01 \x03(\v2%.agentenv.executor.v1.InspectResponseR\x06actors\"\xf0\x01\n" +
	"\x19ApplyNetworkPolicyRequest\x12F\n" +
	"\texecution\x18\x01 \x01(\v2(.agentenv.executor.v1.LifecycleOperationR\texecution\x12\x1b\n" +
	"\tactor_uid\x18\x02 \x01(\tR\bactorUid\x121\n" +
	"\x15target_worker_pod_uid\x18\x03 \x01(\tR\x12targetWorkerPodUid\x12;\n" +
	"\x06policy\x18\x04 \x01(\v2#.agentenv.executor.v1.NetworkPolicyR\x06policy\"G\n" +
	"\x1aApplyNetworkPolicyResponse\x12)\n" +
	"\x10applied_revision\x18\x01 \x01(\x04R\x0fappliedRevision\"\xaf\x01\n" +
	"\x15ReadGuestStatsRequest\x12F\n" +
	"\texecution\x18\x01 \x01(\v2(.agentenv.executor.v1.LifecycleOperationR\texecution\x12\x1b\n" +
	"\tactor_uid\x18\x02 \x01(\tR\bactorUid\x121\n" +
	"\x15target_worker_pod_uid\x18\x03 \x01(\tR\x12targetWorkerPodUid\"\xb0\x01\n" +
	"\x16ReadRuntimeInfoRequest\x12F\n" +
	"\texecution\x18\x01 \x01(\v2(.agentenv.executor.v1.LifecycleOperationR\texecution\x12\x1b\n" +
	"\tactor_uid\x18\x02 \x01(\tR\bactorUid\x121\n" +
	"\x15target_worker_pod_uid\x18\x03 \x01(\tR\x12targetWorkerPodUid\"\xf2\x01\n" +
	"\x1bApplyExtensionParamsRequest\x12F\n" +
	"\texecution\x18\x01 \x01(\v2(.agentenv.executor.v1.LifecycleOperationR\texecution\x12\x1b\n" +
	"\tactor_uid\x18\x02 \x01(\tR\bactorUid\x121\n" +
	"\x15target_worker_pod_uid\x18\x03 \x01(\tR\x12targetWorkerPodUid\x12;\n" +
	"\x05patch\x18\x04 \x01(\v2%.agentenv.executor.v1.ExtensionParamsR\x05patch\"\x97\x01\n" +
	"\x1cApplyExtensionParamsResponse\x12A\n" +
	"\bapproved\x18\x01 \x01(\v2%.agentenv.executor.v1.ExtensionParamsR\bapproved\x124\n" +
	"\x06effect\x18\x02 \x01(\x0e2\x1c.agentenv.executor.v1.EffectR\x06effect*R\n" +
	"\x06Effect\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tNO_EFFECT\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\x12\n" +
	"\x0eEFFECT_UNKNOWN\x10\x032\xd5\x03\n" +
	"\bExecutor\x12e\n" +
	"\fCapabilities\x12).agentenv.executor.v1.CapabilitiesRequest\x1a*.agentenv.executor.v1.CapabilitiesResponse\x12Z\n" +
	"\aExecute\x12&.agentenv.executor.v1.OperationRequest\x1a'.agentenv.executor.v1.OperationResponse\x12V\n" +
	"\aInspect\x12$.agentenv.executor.v1.InspectRequest\x1a%.agentenv.executor.v1.InspectResponse\x12P\n" +
	"\x05Stats\x12\".agentenv.executor.v1.StatsRequest\x1a#.agentenv.executor.v1.StatsResponse\x12\\\n" +
	"\tReconcile\x12&.agentenv.executor.v1.ReconcileRequest\x1a'.agentenv.executor.v1.ReconcileResponseBDZBgithub.com/agent-substrate/substrate/internal/proto/aenvexecutorpbb\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_executor_proto_goTypes = []any{
	(Effect)(0),                          // 0: agentenv.executor.v1.Effect
	(NetworkPolicy_Base)(0),              // 1: agentenv.executor.v1.NetworkPolicy.Base
	(*CapabilitiesRequest)(nil),          // 2: agentenv.executor.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),         // 3: agentenv.executor.v1.CapabilitiesResponse
	(*Fence)(nil),                        // 4: agentenv.executor.v1.Fence
	(*LifecycleOperation)(nil),           // 5: agentenv.executor.v1.LifecycleOperation
	(*OperationRequest)(nil),             // 6: agentenv.executor.v1.OperationRequest
	(*Command)(nil),                      // 7: agentenv.executor.v1.Command
	(*LaunchSpec)(nil),                   // 8: agentenv.executor.v1.LaunchSpec
	(*EnvVar)(nil),                       // 9: agentenv.executor.v1.EnvVar
	(*RuntimeAsset)(nil),                 // 10: agentenv.executor.v1.RuntimeAsset
	(*NetworkAttachment)(nil),            // 11: agentenv.executor.v1.NetworkAttachment
	(*NetworkPolicy)(nil),                // 12: agentenv.executor.v1.NetworkPolicy
	(*ExtensionParams)(nil),              // 13: agentenv.executor.v1.ExtensionParams
	(*Drive)(nil),                        // 14: agentenv.executor.v1.Drive
	(*RestoreSpec)(nil),                  // 15: agentenv.executor.v1.RestoreSpec
	(*CaptureSpec)(nil),                  // 16: agentenv.executor.v1.CaptureSpec
	(*StopSpec)(nil),                     // 17: agentenv.executor.v1.StopSpec
	(*OperationResponse)(nil),            // 18: agentenv.executor.v1.OperationResponse
	(*InspectRequest)(nil),               // 19: agentenv.executor.v1.InspectRequest
	(*InspectResponse)(nil),              // 20: agentenv.executor.v1.InspectResponse
	(*StatsRequest)(nil),                 // 21: agentenv.executor.v1.StatsRequest
	(*StatsResponse)(nil),                // 22: agentenv.executor.v1.StatsResponse
	(*ReconcileRequest)(nil),             // 23: agentenv.executor.v1.ReconcileRequest
	(*ReconcileResponse)(nil),            // 24: agentenv.executor.v1.ReconcileResponse
	(*ApplyNetworkPolicyRequest)(nil),    // 25: agentenv.executor.v1.ApplyNetworkPolicyRequest
	(*ApplyNetworkPolicyResponse)(nil),   // 26: agentenv.executor.v1.ApplyNetworkPolicyResponse
	(*ReadGuestStatsRequest)(nil),        // 27: agentenv.executor.v1.ReadGuestStatsRequest
	(*ReadRuntimeInfoRequest)(nil),       // 28: agentenv.executor.v1.ReadRuntimeInfoRequest
	(*ApplyExtensionParamsRequest)(nil),  // 29: agentenv.executor.v1.ApplyExtensionParamsRequest
	(*ApplyExtensionParamsResponse)(nil), // 30: agentenv.executor.v1.ApplyExtensionParamsResponse
}
var file_executor_proto_depIdxs = []int32{
	4,  // 0: agentenv.executor.v1.LifecycleOperation.fence:type_name -> agentenv.executor.v1.Fence
	4,  // 1: agentenv.executor.v1.OperationRequest.fence:type_name -> agentenv.executor.v1.Fence
	7,  // 2: agentenv.executor.v1.OperationRequest.command:type_name -> agentenv.executor.v1.Command
	8,  // 3: agentenv.executor.v1.Command.start:type_name -> agentenv.executor.v1.LaunchSpec
	15, // 4: agentenv.executor.v1.Command.restore:type_name -> agentenv.executor.v1.RestoreSpec
	16, // 5: agentenv.executor.v1.Command.capture:type_name -> agentenv.executor.v1.CaptureSpec
	17, // 6: agentenv.executor.v1.Command.stop:type_name -> agentenv.executor.v1.StopSpec
	12, // 7: agentenv.executor.v1.Command.update_policy:type_name -> agentenv.executor.v1.NetworkPolicy
	13, // 8: agentenv.executor.v1.Command.update_extensions:type_name -> agentenv.executor.v1.ExtensionParams
	9,  // 9: agentenv.executor.v1.LaunchSpec.env:type_name -> agentenv.executor.v1.EnvVar
	11, // 10: agentenv.executor.v1.LaunchSpec.network:type_name -> agentenv.executor.v1.NetworkAttachment
	10, // 11: agentenv.executor.v1.LaunchSpec.assets:type_name -> agentenv.executor.v1.RuntimeAsset
	14, // 12: agentenv.executor.v1.LaunchSpec.drives:type_name -> agentenv.executor.v1.Drive
	13, // 13: agentenv.executor.v1.LaunchSpec.extensions:type_name -> agentenv.executor.v1.ExtensionParams
	12, // 14: agentenv.executor.v1.NetworkAttachment.policy:type_name -> agentenv.executor.v1.NetworkPolicy
	1,  // 15: agentenv.executor.v1.NetworkPolicy.base:type_name -> agentenv.executor.v1.NetworkPolicy.Base
	8,  // 16: agentenv.executor.v1.RestoreSpec.launch:type_name -> agentenv.executor.v1.LaunchSpec
	0,  // 17: agentenv.executor.v1.OperationResponse.effect:type_name -> agentenv.executor.v1.Effect
	13, // 18: agentenv.executor.v1.OperationResponse.approved_extensions:type_name -> agentenv.executor.v1.ExtensionParams
	4,  // 19: agentenv.executor.v1.InspectRequest.fence:type_name -> agentenv.executor.v1.Fence
	4,  // 20: agentenv.executor.v1.InspectResponse.fence:type_name -> agentenv.executor.v1.Fence
	18, // 21: agentenv.executor.v1.InspectResponse.operation:type_name -> agentenv.executor.v1.OperationResponse
	13, // 22: agentenv.executor.v1.InspectResponse.current_extensions:type_name -> agentenv.executor.v1.ExtensionParams
	4,  // 23: agentenv.executor.v1.StatsRequest.fence:type_name -> agentenv.executor.v1.Fence
	4,  // 24: agentenv.executor.v1.StatsResponse.fence:type_name -> agentenv.executor.v1.Fence
	4,  // 25: agentenv.executor.v1.ReconcileRequest.assignments:type_name -> agentenv.executor.v1.Fence
	20, // 26: agentenv.executor.v1.ReconcileResponse.actors:type_name -> agentenv.executor.v1.InspectResponse
	5,  // 27: agentenv.executor.v1.ApplyNetworkPolicyRequest.execution:type_name -> agentenv.executor.v1.LifecycleOperation
	12, // 28: agentenv.executor.v1.ApplyNetworkPolicyRequest.policy:type_name -> agentenv.executor.v1.NetworkPolicy
	5,  // 29: agentenv.executor.v1.ReadGuestStatsRequest.execution:type_name -> agentenv.executor.v1.LifecycleOperation
	5,  // 30: agentenv.executor.v1.ReadRuntimeInfoRequest.execution:type_name -> agentenv.executor.v1.LifecycleOperation
	5,  // 31: agentenv.executor.v1.ApplyExtensionParamsRequest.execution:type_name -> agentenv.executor.v1.LifecycleOperation
	13, // 32: agentenv.executor.v1.ApplyExtensionParamsRequest.patch:type_name -> agentenv.executor.v1.ExtensionParams
	13, // 33: agentenv.executor.v1.ApplyExtensionParamsResponse.approved:type_name -> agentenv.executor.v1.ExtensionParams
	0,  // 34: agentenv.executor.v1.ApplyExtensionParamsResponse.effect:type_name -> agentenv.executor.v1.Effect
	2,  // 35: agentenv.executor.v1.Executor.Capabilities:input_type -> agentenv.executor.v1.CapabilitiesRequest
	6,  // 36: agentenv.executor.v1.Executor.Execute:input_type -> agentenv.executor.v1.OperationRequest
	19, // 37: agentenv.executor.v1.Executor.Inspect:input_type -> agentenv.executor.v1.InspectRequest
	21, // 38: agentenv.executor.v1.Executor.Stats:input_type -> agentenv.executor.v1.StatsRequest
	23, // 39: agentenv.executor.v1.Executor.Reconcile:input_type -> agentenv.executor.v1.ReconcileRequest
	3,  // 40: agentenv.executor.v1.Executor.Capabilities:output_type -> agentenv.executor.v1.CapabilitiesResponse
	18, // 41: agentenv.executor.v1.Executor.Execute:output_type -> agentenv.executor.v1.OperationResponse
	20, // 42: agentenv.executor.v1.Executor.Inspect:output_type -> agentenv.executor.v1.InspectResponse
	22, // 43: agentenv.executor.v1.Executor.Stats:output_type -> agentenv.executor.v1.StatsResponse
	24, // 44: agentenv.executor.v1.Executor.Reconcile:output_type -> agentenv.executor.v1.ReconcileResponse
	40, // [40:45] is the sub-list for method output_type
	35, // [35:40] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	file_executor_proto_msgTypes[5].OneofWrappers = []any{
		(*Command_Start)(nil),
		(*Command_Restore)(nil),
		(*Command_Capture)(nil),
		(*Command_Stop)(nil),
		(*Command_UpdatePolicy)(nil),
		(*Command_UpdateExtensions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		EnumInfos:         file_executor_proto_enumTypes,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
