// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: ateom.proto

package ateompb

import (
	context "context"
	aenvexecutorpb "github.com/agent-substrate/substrate/internal/proto/aenvexecutorpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ateom_ReadRuntimeInfo_FullMethodName        = "/ateom.Ateom/ReadRuntimeInfo"
	Ateom_ReadGuestStats_FullMethodName         = "/ateom.Ateom/ReadGuestStats"
	Ateom_ApplyNetworkPolicy_FullMethodName     = "/ateom.Ateom/ApplyNetworkPolicy"
	Ateom_ApplyExtensionParams_FullMethodName   = "/ateom.Ateom/ApplyExtensionParams"
	Ateom_RunWorkload_FullMethodName            = "/ateom.Ateom/RunWorkload"
	Ateom_CheckpointWorkload_FullMethodName     = "/ateom.Ateom/CheckpointWorkload"
	Ateom_CaptureWorkload_FullMethodName        = "/ateom.Ateom/CaptureWorkload"
	Ateom_RestoreWorkload_FullMethodName        = "/ateom.Ateom/RestoreWorkload"
	Ateom_GetWorkloadStats_FullMethodName       = "/ateom.Ateom/GetWorkloadStats"
	Ateom_GetActiveWorkloadStats_FullMethodName = "/ateom.Ateom/GetActiveWorkloadStats"
	Ateom_TerminateWorkload_FullMethodName      = "/ateom.Ateom/TerminateWorkload"
)

// AteomClient is the client API for Ateom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ateom is the interface to control a single gVisor (or, in the future microVM)
// guest inside a worker pod.
//
// Each ateom server has two main states, "available" and "executing".
//
// When the ateom is "available", the substrate control plane is free to either
// boot a new workload (using RunWorkload), or restore an existing workload from
// a checkpoint (using RestoreWorkload).  These calls move the ateom into
// "executing" state.
//
// When the ateom is "executing", the substrate control plane can checkpoint the
// running workload (with CheckpointWorkload).  This moves the ateom back to
// "free" state.
type AteomClient interface {
	// Allocation-fenced runtime metadata; contains no access credentials.
	ReadRuntimeInfo(ctx context.Context, in *aenvexecutorpb.ReadRuntimeInfoRequest, opts ...grpc.CallOption) (*aenvexecutorpb.InspectResponse, error)
	// AgentENV guest measurements, distinct from host cgroup consumption.
	ReadGuestStats(ctx context.Context, in *aenvexecutorpb.ReadGuestStatsRequest, opts ...grpc.CallOption) (*aenvexecutorpb.StatsResponse, error)
	// AgentENV-only live policy mutation; success confirms the exact revision.
	ApplyNetworkPolicy(ctx context.Context, in *aenvexecutorpb.ApplyNetworkPolicyRequest, opts ...grpc.CallOption) (*aenvexecutorpb.ApplyNetworkPolicyResponse, error)
	ApplyExtensionParams(ctx context.Context, in *aenvexecutorpb.ApplyExtensionParamsRequest, opts ...grpc.CallOption) (*aenvexecutorpb.ApplyExtensionParamsResponse, error)
	// RunWorkload tells ateom to begin running a new workload (one or more
	// containers, potentially with shared filesystems).
	RunWorkload(ctx context.Context, in *RunWorkloadRequest, opts ...grpc.CallOption) (*RunWorkloadResponse, error)
	// CheckpointWorkload tells ateom to save the current state of the running
	// workload to object storage, and then completely reset itself to a blank
	// state (back to "available" state.)
	CheckpointWorkload(ctx context.Context, in *CheckpointWorkloadRequest, opts ...grpc.CallOption) (*CheckpointWorkloadResponse, error)
	// Capture FULL AgentENV state while keeping the source workload running.
	// The caller supplies an operation-specific checkpoint directory.
	CaptureWorkload(ctx context.Context, in *CheckpointWorkloadRequest, opts ...grpc.CallOption) (*CheckpointWorkloadResponse, error)
	// RestoreWorkload restores a workload from checkpoint that was previously
	// written by CheckpointWorkload.  Ateom will handle downloading the correct
	// gVisor / runsc version to match the checkpoint.
	RestoreWorkload(ctx context.Context, in *RestoreWorkloadRequest, opts ...grpc.CallOption) (*RestoreWorkloadResponse, error)
	// GetWorkloadStats returns a point-in-time resource-usage sample for the
	// workload this ateom is currently executing.
	//
	// It is a pure read: unlike the three calls above it does not move the ateom
	// between "available" and "executing", so it is safe to call on a timer for
	// the whole lifetime of a workload. It also does not wait on them. Those
	// three serialize on a mutex an ateom holds for a whole boot, restore, or
	// checkpoint; this call reads its state from outside that mutex, so a poll
	// landing in the middle of one answers immediately instead of going quiet for
	// the duration -- which would silence the poller during exactly the phases
	// whose usage is most interesting.
	//
	// Two ways it declines to give a sample, and they ask different things of the
	// caller:
	//
	//   * NOT_FOUND -- this ateom is not executing the actor in the request. It
	//     may be "available", or a recycled worker may have moved on to a
	//     different actor. Retrying on the same timer will not change the answer:
	//     the caller's worker-to-actor mapping is stale and wants re-resolving.
	//
	//   * FAILED_PRECONDITION -- this ateom is executing the requested actor but
	//     has no sample to give yet. It accepts an actor before the sandbox it
	//     will measure exists, so a poll landing in the boot lands here. Read it
	//     as "no numbers right now", not as "the actor is gone": it is transient,
	//     and the caller should skip this sample and take the next one.
	//
	// The split is worth the two codes because the identity is retained from the
	// moment the ateom accepts the actor, on both runtimes. That is what makes
	// "booting" distinguishable from "not here" at all, and it means a workload
	// that dies during boot is attributable rather than anonymous.
	GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*GetWorkloadStatsResponse, error)
	// GetActiveWorkloadStats samples whatever this ateom is currently
	// executing, without asserting an identity. It is the discovery read for a
	// scraper that enumerates ateoms and holds no worker-to-actor mapping;
	// GetWorkloadStats above is the verified read for a caller that must be
	// answered about a specific actor.
	//
	// Every state a blind caller can find is a normal answer here, never an
	// error: an "available" ateom answers an empty samples list, and a workload
	// with nothing to measure YET (a poll landing in a boot or a restore)
	// appears as a sample carrying its attribution with
	// source = STATS_SOURCE_UNSPECIFIED -- "not measured", per the sample's own
	// contract -- so even a workload that dies during boot is attributable, not
	// anonymous. Error codes are reserved for real failures reading a sandbox
	// that should be measurable. This is deliberately unlike GetWorkloadStats,
	// whose caller asserts knowledge the codes then answer.
	//
	// Consumers MUST attribute each sample solely from the identity echoed
	// inside it, never from a mapping they hold: without an asserted uid, the
	// response is the only statement of who was measured. Like GetWorkloadStats
	// it is a pure read, safe on a timer, and does not touch the lifecycle
	// mutex.
	GetActiveWorkloadStats(ctx context.Context, in *GetActiveWorkloadStatsRequest, opts ...grpc.CallOption) (*GetActiveWorkloadStatsResponse, error)
	// TerminateWorkload stops and deletes container workloads and cleans up
	// network and bundle overlays on ateom.
	TerminateWorkload(ctx context.Context, in *TerminateWorkloadRequest, opts ...grpc.CallOption) (*TerminateWorkloadResponse, error)
}

type ateomClient struct {
	cc grpc.ClientConnInterface
}

func NewAteomClient(cc grpc.ClientConnInterface) AteomClient {
	return &ateomClient{cc}
}

func (c *ateomClient) ReadRuntimeInfo(ctx context.Context, in *aenvexecutorpb.ReadRuntimeInfoRequest, opts ...grpc.CallOption) (*aenvexecutorpb.InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(aenvexecutorpb.InspectResponse)
	err := c.cc.Invoke(ctx, Ateom_ReadRuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) ReadGuestStats(ctx context.Context, in *aenvexecutorpb.ReadGuestStatsRequest, opts ...grpc.CallOption) (*aenvexecutorpb.StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(aenvexecutorpb.StatsResponse)
	err := c.cc.Invoke(ctx, Ateom_ReadGuestStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) ApplyNetworkPolicy(ctx context.Context, in *aenvexecutorpb.ApplyNetworkPolicyRequest, opts ...grpc.CallOption) (*aenvexecutorpb.ApplyNetworkPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(aenvexecutorpb.ApplyNetworkPolicyResponse)
	err := c.cc.Invoke(ctx, Ateom_ApplyNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) ApplyExtensionParams(ctx context.Context, in *aenvexecutorpb.ApplyExtensionParamsRequest, opts ...grpc.CallOption) (*aenvexecutorpb.ApplyExtensionParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(aenvexecutorpb.ApplyExtensionParamsResponse)
	err := c.cc.Invoke(ctx, Ateom_ApplyExtensionParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) RunWorkload(ctx context.Context, in *RunWorkloadRequest, opts ...grpc.CallOption) (*RunWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWorkloadResponse)
	err := c.cc.Invoke(ctx, Ateom_RunWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) CheckpointWorkload(ctx context.Context, in *CheckpointWorkloadRequest, opts ...grpc.CallOption) (*CheckpointWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointWorkloadResponse)
	err := c.cc.Invoke(ctx, Ateom_CheckpointWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) CaptureWorkload(ctx context.Context, in *CheckpointWorkloadRequest, opts ...grpc.CallOption) (*CheckpointWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointWorkloadResponse)
	err := c.cc.Invoke(ctx, Ateom_CaptureWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) RestoreWorkload(ctx context.Context, in *RestoreWorkloadRequest, opts ...grpc.CallOption) (*RestoreWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreWorkloadResponse)
	err := c.cc.Invoke(ctx, Ateom_RestoreWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*GetWorkloadStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadStatsResponse)
	err := c.cc.Invoke(ctx, Ateom_GetWorkloadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) GetActiveWorkloadStats(ctx context.Context, in *GetActiveWorkloadStatsRequest, opts ...grpc.CallOption) (*GetActiveWorkloadStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveWorkloadStatsResponse)
	err := c.cc.Invoke(ctx, Ateom_GetActiveWorkloadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomClient) TerminateWorkload(ctx context.Context, in *TerminateWorkloadRequest, opts ...grpc.CallOption) (*TerminateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateWorkloadResponse)
	err := c.cc.Invoke(ctx, Ateom_TerminateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AteomServer is the server API for Ateom service.
// All implementations must embed UnimplementedAteomServer
// for forward compatibility.
//
// Ateom is the interface to control a single gVisor (or, in the future microVM)
// guest inside a worker pod.
//
// Each ateom server has two main states, "available" and "executing".
//
// When the ateom is "available", the substrate control plane is free to either
// boot a new workload (using RunWorkload), or restore an existing workload from
// a checkpoint (using RestoreWorkload).  These calls move the ateom into
// "executing" state.
//
// When the ateom is "executing", the substrate control plane can checkpoint the
// running workload (with CheckpointWorkload).  This moves the ateom back to
// "free" state.
type AteomServer interface {
	// Allocation-fenced runtime metadata; contains no access credentials.
	ReadRuntimeInfo(context.Context, *aenvexecutorpb.ReadRuntimeInfoRequest) (*aenvexecutorpb.InspectResponse, error)
	// AgentENV guest measurements, distinct from host cgroup consumption.
	ReadGuestStats(context.Context, *aenvexecutorpb.ReadGuestStatsRequest) (*aenvexecutorpb.StatsResponse, error)
	// AgentENV-only live policy mutation; success confirms the exact revision.
	ApplyNetworkPolicy(context.Context, *aenvexecutorpb.ApplyNetworkPolicyRequest) (*aenvexecutorpb.ApplyNetworkPolicyResponse, error)
	ApplyExtensionParams(context.Context, *aenvexecutorpb.ApplyExtensionParamsRequest) (*aenvexecutorpb.ApplyExtensionParamsResponse, error)
	// RunWorkload tells ateom to begin running a new workload (one or more
	// containers, potentially with shared filesystems).
	RunWorkload(context.Context, *RunWorkloadRequest) (*RunWorkloadResponse, error)
	// CheckpointWorkload tells ateom to save the current state of the running
	// workload to object storage, and then completely reset itself to a blank
	// state (back to "available" state.)
	CheckpointWorkload(context.Context, *CheckpointWorkloadRequest) (*CheckpointWorkloadResponse, error)
	// Capture FULL AgentENV state while keeping the source workload running.
	// The caller supplies an operation-specific checkpoint directory.
	CaptureWorkload(context.Context, *CheckpointWorkloadRequest) (*CheckpointWorkloadResponse, error)
	// RestoreWorkload restores a workload from checkpoint that was previously
	// written by CheckpointWorkload.  Ateom will handle downloading the correct
	// gVisor / runsc version to match the checkpoint.
	RestoreWorkload(context.Context, *RestoreWorkloadRequest) (*RestoreWorkloadResponse, error)
	// GetWorkloadStats returns a point-in-time resource-usage sample for the
	// workload this ateom is currently executing.
	//
	// It is a pure read: unlike the three calls above it does not move the ateom
	// between "available" and "executing", so it is safe to call on a timer for
	// the whole lifetime of a workload. It also does not wait on them. Those
	// three serialize on a mutex an ateom holds for a whole boot, restore, or
	// checkpoint; this call reads its state from outside that mutex, so a poll
	// landing in the middle of one answers immediately instead of going quiet for
	// the duration -- which would silence the poller during exactly the phases
	// whose usage is most interesting.
	//
	// Two ways it declines to give a sample, and they ask different things of the
	// caller:
	//
	//   * NOT_FOUND -- this ateom is not executing the actor in the request. It
	//     may be "available", or a recycled worker may have moved on to a
	//     different actor. Retrying on the same timer will not change the answer:
	//     the caller's worker-to-actor mapping is stale and wants re-resolving.
	//
	//   * FAILED_PRECONDITION -- this ateom is executing the requested actor but
	//     has no sample to give yet. It accepts an actor before the sandbox it
	//     will measure exists, so a poll landing in the boot lands here. Read it
	//     as "no numbers right now", not as "the actor is gone": it is transient,
	//     and the caller should skip this sample and take the next one.
	//
	// The split is worth the two codes because the identity is retained from the
	// moment the ateom accepts the actor, on both runtimes. That is what makes
	// "booting" distinguishable from "not here" at all, and it means a workload
	// that dies during boot is attributable rather than anonymous.
	GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*GetWorkloadStatsResponse, error)
	// GetActiveWorkloadStats samples whatever this ateom is currently
	// executing, without asserting an identity. It is the discovery read for a
	// scraper that enumerates ateoms and holds no worker-to-actor mapping;
	// GetWorkloadStats above is the verified read for a caller that must be
	// answered about a specific actor.
	//
	// Every state a blind caller can find is a normal answer here, never an
	// error: an "available" ateom answers an empty samples list, and a workload
	// with nothing to measure YET (a poll landing in a boot or a restore)
	// appears as a sample carrying its attribution with
	// source = STATS_SOURCE_UNSPECIFIED -- "not measured", per the sample's own
	// contract -- so even a workload that dies during boot is attributable, not
	// anonymous. Error codes are reserved for real failures reading a sandbox
	// that should be measurable. This is deliberately unlike GetWorkloadStats,
	// whose caller asserts knowledge the codes then answer.
	//
	// Consumers MUST attribute each sample solely from the identity echoed
	// inside it, never from a mapping they hold: without an asserted uid, the
	// response is the only statement of who was measured. Like GetWorkloadStats
	// it is a pure read, safe on a timer, and does not touch the lifecycle
	// mutex.
	GetActiveWorkloadStats(context.Context, *GetActiveWorkloadStatsRequest) (*GetActiveWorkloadStatsResponse, error)
	// TerminateWorkload stops and deletes container workloads and cleans up
	// network and bundle overlays on ateom.
	TerminateWorkload(context.Context, *TerminateWorkloadRequest) (*TerminateWorkloadResponse, error)
	mustEmbedUnimplementedAteomServer()
}

// UnimplementedAteomServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAteomServer struct{}

func (UnimplementedAteomServer) ReadRuntimeInfo(context.Context, *aenvexecutorpb.ReadRuntimeInfoRequest) (*aenvexecutorpb.InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadRuntimeInfo not implemented")
}
func (UnimplementedAteomServer) ReadGuestStats(context.Context, *aenvexecutorpb.ReadGuestStatsRequest) (*aenvexecutorpb.StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadGuestStats not implemented")
}
func (UnimplementedAteomServer) ApplyNetworkPolicy(context.Context, *aenvexecutorpb.ApplyNetworkPolicyRequest) (*aenvexecutorpb.ApplyNetworkPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNetworkPolicy not implemented")
}
func (UnimplementedAteomServer) ApplyExtensionParams(context.Context, *aenvexecutorpb.ApplyExtensionParamsRequest) (*aenvexecutorpb.ApplyExtensionParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyExtensionParams not implemented")
}
func (UnimplementedAteomServer) RunWorkload(context.Context, *RunWorkloadRequest) (*RunWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkload not implemented")
}
func (UnimplementedAteomServer) CheckpointWorkload(context.Context, *CheckpointWorkloadRequest) (*CheckpointWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointWorkload not implemented")
}
func (UnimplementedAteomServer) CaptureWorkload(context.Context, *CheckpointWorkloadRequest) (*CheckpointWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureWorkload not implemented")
}
func (UnimplementedAteomServer) RestoreWorkload(context.Context, *RestoreWorkloadRequest) (*RestoreWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreWorkload not implemented")
}
func (UnimplementedAteomServer) GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*GetWorkloadStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkloadStats not implemented")
}
func (UnimplementedAteomServer) GetActiveWorkloadStats(context.Context, *GetActiveWorkloadStatsRequest) (*GetActiveWorkloadStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveWorkloadStats not implemented")
}
func (UnimplementedAteomServer) TerminateWorkload(context.Context, *TerminateWorkloadRequest) (*TerminateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateWorkload not implemented")
}
func (UnimplementedAteomServer) mustEmbedUnimplementedAteomServer() {}
func (UnimplementedAteomServer) testEmbeddedByValue()               {}

// UnsafeAteomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AteomServer will
// result in compilation errors.
type UnsafeAteomServer interface {
	mustEmbedUnimplementedAteomServer()
}

func RegisterAteomServer(s grpc.ServiceRegistrar, srv AteomServer) {
	// If the following call panics, it indicates UnimplementedAteomServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ateom_ServiceDesc, srv)
}

func _Ateom_ReadRuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aenvexecutorpb.ReadRuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).ReadRuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_ReadRuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).ReadRuntimeInfo(ctx, req.(*aenvexecutorpb.ReadRuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_ReadGuestStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aenvexecutorpb.ReadGuestStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).ReadGuestStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_ReadGuestStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).ReadGuestStats(ctx, req.(*aenvexecutorpb.ReadGuestStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_ApplyNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aenvexecutorpb.ApplyNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).ApplyNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_ApplyNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).ApplyNetworkPolicy(ctx, req.(*aenvexecutorpb.ApplyNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_ApplyExtensionParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aenvexecutorpb.ApplyExtensionParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).ApplyExtensionParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_ApplyExtensionParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).ApplyExtensionParams(ctx, req.(*aenvexecutorpb.ApplyExtensionParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_RunWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).RunWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_RunWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).RunWorkload(ctx, req.(*RunWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_CheckpointWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).CheckpointWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_CheckpointWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).CheckpointWorkload(ctx, req.(*CheckpointWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_CaptureWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).CaptureWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_CaptureWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).CaptureWorkload(ctx, req.(*CheckpointWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_RestoreWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).RestoreWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_RestoreWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).RestoreWorkload(ctx, req.(*RestoreWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_GetWorkloadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).GetWorkloadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_GetWorkloadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).GetWorkloadStats(ctx, req.(*GetWorkloadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_GetActiveWorkloadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveWorkloadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).GetActiveWorkloadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_GetActiveWorkloadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).GetActiveWorkloadStats(ctx, req.(*GetActiveWorkloadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ateom_TerminateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomServer).TerminateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ateom_TerminateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomServer).TerminateWorkload(ctx, req.(*TerminateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ateom_ServiceDesc is the grpc.ServiceDesc for Ateom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ateom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateom.Ateom",
	HandlerType: (*AteomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadRuntimeInfo",
			Handler:    _Ateom_ReadRuntimeInfo_Handler,
		},
		{
			MethodName: "ReadGuestStats",
			Handler:    _Ateom_ReadGuestStats_Handler,
		},
		{
			MethodName: "ApplyNetworkPolicy",
			Handler:    _Ateom_ApplyNetworkPolicy_Handler,
		},
		{
			MethodName: "ApplyExtensionParams",
			Handler:    _Ateom_ApplyExtensionParams_Handler,
		},
		{
			MethodName: "RunWorkload",
			Handler:    _Ateom_RunWorkload_Handler,
		},
		{
			MethodName: "CheckpointWorkload",
			Handler:    _Ateom_CheckpointWorkload_Handler,
		},
		{
			MethodName: "CaptureWorkload",
			Handler:    _Ateom_CaptureWorkload_Handler,
		},
		{
			MethodName: "RestoreWorkload",
			Handler:    _Ateom_RestoreWorkload_Handler,
		},
		{
			MethodName: "GetWorkloadStats",
			Handler:    _Ateom_GetWorkloadStats_Handler,
		},
		{
			MethodName: "GetActiveWorkloadStats",
			Handler:    _Ateom_GetActiveWorkloadStats_Handler,
		},
		{
			MethodName: "TerminateWorkload",
			Handler:    _Ateom_TerminateWorkload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ateom.proto",
}
