// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: objectstoresnapshot.proto

package objectstoresnapshotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeProvider_FetchSnapshot_FullMethodName  = "/objectstoresnapshot.v1.NodeProvider/FetchSnapshot"
	NodeProvider_UploadSnapshot_FullMethodName = "/objectstoresnapshot.v1.NodeProvider/UploadSnapshot"
)

// NodeProviderClient is the client API for NodeProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeProvider is the plugin API an object storage platform implements
// on every node. atelet calls it to move actor snapshots between the node and
// the platform's object storage. How the platform stores them (object names,
// compression) is private to the plugin. The only requirement is that
// FetchSnapshot returns the bytes UploadSnapshot was given. Substrate stores
// no checksums; verifying integrity is up to the plugin.
//
// Callers name every file they want moved. A snapshot's file list lives in
// its manifest, which the caller fetches first by name. The caller also owns
// commit ordering: it uploads the data files, and only after that call
// succeeds does it upload the manifest in a separate call, so a reader that
// finds the manifest can rely on every file it lists.
//
// Every RPC is idempotent: a retry overwrites whatever an earlier attempt
// stored or wrote.
type NodeProviderClient interface {
	// FetchSnapshot downloads the named files of a snapshot into write_path.
	// It returns NOT_FOUND if any requested file is absent from the snapshot.
	// A plugin that authorizes per actor returns PERMISSION_DENIED if actor_jwt
	// does not grant read access to snapshot_uri.
	FetchSnapshot(ctx context.Context, in *FetchSnapshotRequest, opts ...grpc.CallOption) (*FetchSnapshotResponse, error)
	// UploadSnapshot uploads the named files from local_path into a snapshot.
	// It returns success only once every file is durably stored. On failure,
	// files already stored may remain, and the caller can remove them with
	// ControlProvider.CleanupSnapshot. A plugin that authorizes per actor returns
	// PERMISSION_DENIED if actor_jwt does not grant write access to snapshot_uri.
	UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*UploadSnapshotResponse, error)
}

type nodeProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeProviderClient(cc grpc.ClientConnInterface) NodeProviderClient {
	return &nodeProviderClient{cc}
}

func (c *nodeProviderClient) FetchSnapshot(ctx context.Context, in *FetchSnapshotRequest, opts ...grpc.CallOption) (*FetchSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeProvider_FetchSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeProviderClient) UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*UploadSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeProvider_UploadSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeProviderServer is the server API for NodeProvider service.
// All implementations must embed UnimplementedNodeProviderServer
// for forward compatibility.
//
// NodeProvider is the plugin API an object storage platform implements
// on every node. atelet calls it to move actor snapshots between the node and
// the platform's object storage. How the platform stores them (object names,
// compression) is private to the plugin. The only requirement is that
// FetchSnapshot returns the bytes UploadSnapshot was given. Substrate stores
// no checksums; verifying integrity is up to the plugin.
//
// Callers name every file they want moved. A snapshot's file list lives in
// its manifest, which the caller fetches first by name. The caller also owns
// commit ordering: it uploads the data files, and only after that call
// succeeds does it upload the manifest in a separate call, so a reader that
// finds the manifest can rely on every file it lists.
//
// Every RPC is idempotent: a retry overwrites whatever an earlier attempt
// stored or wrote.
type NodeProviderServer interface {
	// FetchSnapshot downloads the named files of a snapshot into write_path.
	// It returns NOT_FOUND if any requested file is absent from the snapshot.
	// A plugin that authorizes per actor returns PERMISSION_DENIED if actor_jwt
	// does not grant read access to snapshot_uri.
	FetchSnapshot(context.Context, *FetchSnapshotRequest) (*FetchSnapshotResponse, error)
	// UploadSnapshot uploads the named files from local_path into a snapshot.
	// It returns success only once every file is durably stored. On failure,
	// files already stored may remain, and the caller can remove them with
	// ControlProvider.CleanupSnapshot. A plugin that authorizes per actor returns
	// PERMISSION_DENIED if actor_jwt does not grant write access to snapshot_uri.
	UploadSnapshot(context.Context, *UploadSnapshotRequest) (*UploadSnapshotResponse, error)
	mustEmbedUnimplementedNodeProviderServer()
}

// UnimplementedNodeProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeProviderServer struct{}

func (UnimplementedNodeProviderServer) FetchSnapshot(context.Context, *FetchSnapshotRequest) (*FetchSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchSnapshot not implemented")
}
func (UnimplementedNodeProviderServer) UploadSnapshot(context.Context, *UploadSnapshotRequest) (*UploadSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSnapshot not implemented")
}
func (UnimplementedNodeProviderServer) mustEmbedUnimplementedNodeProviderServer() {}
func (UnimplementedNodeProviderServer) testEmbeddedByValue()                      {}

// UnsafeNodeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeProviderServer will
// result in compilation errors.
type UnsafeNodeProviderServer interface {
	mustEmbedUnimplementedNodeProviderServer()
}

func RegisterNodeProviderServer(s grpc.ServiceRegistrar, srv NodeProviderServer) {
	// If the following call panics, it indicates UnimplementedNodeProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeProvider_ServiceDesc, srv)
}

func _NodeProvider_FetchSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeProviderServer).FetchSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeProvider_FetchSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeProviderServer).FetchSnapshot(ctx, req.(*FetchSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeProvider_UploadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeProviderServer).UploadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeProvider_UploadSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeProviderServer).UploadSnapshot(ctx, req.(*UploadSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeProvider_ServiceDesc is the grpc.ServiceDesc for NodeProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "objectstoresnapshot.v1.NodeProvider",
	HandlerType: (*NodeProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchSnapshot",
			Handler:    _NodeProvider_FetchSnapshot_Handler,
		},
		{
			MethodName: "UploadSnapshot",
			Handler:    _NodeProvider_UploadSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objectstoresnapshot.proto",
}

const (
	ControlProvider_CleanupSnapshot_FullMethodName = "/objectstoresnapshot.v1.ControlProvider/CleanupSnapshot"
	ControlProvider_CopySnapshot_FullMethodName    = "/objectstoresnapshot.v1.ControlProvider/CopySnapshot"
)

// ControlProviderClient is the client API for ControlProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlProvider is the plugin API an object storage platform
// implements for the control plane. ate-api-server calls it to manage whole
// snapshots.
type ControlProviderClient interface {
	// CleanupSnapshot deletes every file of a snapshot, or of every snapshot
	// under an owner's prefix. Deleting an absent snapshot succeeds.
	CleanupSnapshot(ctx context.Context, in *CleanupSnapshotRequest, opts ...grpc.CallOption) (*CleanupSnapshotResponse, error)
	// CopySnapshot copies every file of src_uri to dst_uri, overwriting files
	// already at dst_uri. src_uri and dst_uri may be in different buckets. It
	// returns FAILED_PRECONDITION if src_uri holds no files.
	CopySnapshot(ctx context.Context, in *CopySnapshotRequest, opts ...grpc.CallOption) (*CopySnapshotResponse, error)
}

type controlProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewControlProviderClient(cc grpc.ClientConnInterface) ControlProviderClient {
	return &controlProviderClient{cc}
}

func (c *controlProviderClient) CleanupSnapshot(ctx context.Context, in *CleanupSnapshotRequest, opts ...grpc.CallOption) (*CleanupSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupSnapshotResponse)
	err := c.cc.Invoke(ctx, ControlProvider_CleanupSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlProviderClient) CopySnapshot(ctx context.Context, in *CopySnapshotRequest, opts ...grpc.CallOption) (*CopySnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopySnapshotResponse)
	err := c.cc.Invoke(ctx, ControlProvider_CopySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlProviderServer is the server API for ControlProvider service.
// All implementations must embed UnimplementedControlProviderServer
// for forward compatibility.
//
// ControlProvider is the plugin API an object storage platform
// implements for the control plane. ate-api-server calls it to manage whole
// snapshots.
type ControlProviderServer interface {
	// CleanupSnapshot deletes every file of a snapshot, or of every snapshot
	// under an owner's prefix. Deleting an absent snapshot succeeds.
	CleanupSnapshot(context.Context, *CleanupSnapshotRequest) (*CleanupSnapshotResponse, error)
	// CopySnapshot copies every file of src_uri to dst_uri, overwriting files
	// already at dst_uri. src_uri and dst_uri may be in different buckets. It
	// returns FAILED_PRECONDITION if src_uri holds no files.
	CopySnapshot(context.Context, *CopySnapshotRequest) (*CopySnapshotResponse, error)
	mustEmbedUnimplementedControlProviderServer()
}

// UnimplementedControlProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlProviderServer struct{}

func (UnimplementedControlProviderServer) CleanupSnapshot(context.Context, *CleanupSnapshotRequest) (*CleanupSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupSnapshot not implemented")
}
func (UnimplementedControlProviderServer) CopySnapshot(context.Context, *CopySnapshotRequest) (*CopySnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopySnapshot not implemented")
}
func (UnimplementedControlProviderServer) mustEmbedUnimplementedControlProviderServer() {}
func (UnimplementedControlProviderServer) testEmbeddedByValue()                         {}

// UnsafeControlProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlProviderServer will
// result in compilation errors.
type UnsafeControlProviderServer interface {
	mustEmbedUnimplementedControlProviderServer()
}

func RegisterControlProviderServer(s grpc.ServiceRegistrar, srv ControlProviderServer) {
	// If the following call panics, it indicates UnimplementedControlProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlProvider_ServiceDesc, srv)
}

func _ControlProvider_CleanupSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlProviderServer).CleanupSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlProvider_CleanupSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlProviderServer).CleanupSnapshot(ctx, req.(*CleanupSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlProvider_CopySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlProviderServer).CopySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlProvider_CopySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlProviderServer).CopySnapshot(ctx, req.(*CopySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlProvider_ServiceDesc is the grpc.ServiceDesc for ControlProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "objectstoresnapshot.v1.ControlProvider",
	HandlerType: (*ControlProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CleanupSnapshot",
			Handler:    _ControlProvider_CleanupSnapshot_Handler,
		},
		{
			MethodName: "CopySnapshot",
			Handler:    _ControlProvider_CopySnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objectstoresnapshot.proto",
}
